config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/pages/1')
  get '/novations/archives' => 'novations#archives', as: :archives
  resources :articles
  resources :novations
  resources :pages do
    resources :articles
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :page, touch: true

  validates :item, presence: true
  validates :description, presence: true
  validates :page_id, presence: true
end

app/models/novation.rb
class Novation < ActiveRecord::Base
  belongs_to :page

  validates :heading, presence: true
  validates :subject, presence: true
  validates :page_id, presence: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :articles
  has_many :novations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @article = Article.all
  end

  def new
    @page = Page.find(params[:page_id])
    @page.articles.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @page = Page.find(params[:page_id])
    @article = @page.articles.create(article_params)
    #@article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def last_update
    @a= @article.last.updated_at.strftime("%d.%m.%Y")
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      #redirect_to(:action => 'show', :id => @article.id)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:item, :description)
    end
end

app/controllers/novations_controller.rb
class NovationsController < ApplicationController
  def index
    @novations = Novation.all.order("created_at DESC")
  end

  def show
    @novation = Novation.find(params[:id])
  end
  
  def new
    @novation = Novation.new
  end

  def create
    @novation = Novation.new(novation_params)
    if @novation.save
      redirect_to '/pages/3'
      #redirect_to :controller => 'pages', :action => 'show', :id => 1
    else
      render 'new'
    end
  end

  def edit
    @novation = Novation.find(params[:id])
  end

  def update
    @novation = Novation.find(params[:id])
    if @novation.update_attributes(novation_params)
      #redirect_to(:action => 'show', :id => @article.id)
      redirect_to '/pages/3'
    else
      render 'edit'
    end
  end

  def destroy
    @novation = Novation.find(params[:id])
    @novation.destroy
    redirect_to '/pages/3'
  end

  def archives
    @novations = Novation.order("created_at DESC")
  end

  private
    def novation_params
      params.require(:novation).permit(:heading, :subject, :page_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all.order("title ASC")
  end

  def show
    @page = Page.find(params[:id])
    @articles = @page.articles
    @novations = @page.novations
    @pages = Page.all.order("title ASC")
    @novations = Novation.where('created_at > ?', 1.year.ago).order("created_at DESC") if @page.title == "Novations"
    @current_year = Time.now.year
    @today = Time.now.strftime("%d.%m.%Y")
    @articles = Article.all if @page.title == "Articles"
  end
  
  def new
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(page_params)
      redirect_to Page.find(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to root_path
  end

  private
    def page_params
      params.require(:page).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'Travnoe'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/novations_helper.rb
module NovationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Editing Article</h1>
<%= form_for(@article) do |f| %>
<p>
<%= f.text_field :item %>
</p>
<%= f.text_area :description %><br>
<%= f.submit "Update" %>
<% end %>

<p>
  <%= link_to 'Back', :back %>
</p>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for([@page, @page.articles.build]) do |f| %>
 
  <p>
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<p>
  <%= link_to 'Back', :back %> <!--novations_path-->
</p>

app/views/layouts/_footer.html.erb
<footer class="footer container">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <!--<nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>-->
  <div id="copyright">
    &#9426; MKOU, 2008-<%= @current_year %>
  </div>
</footer>

<!--<div class="container-fluid footer-wrap long-art"></div>-->
<div class="footer-image"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>
  

app/views/novations/archives.html.erb
<h3>Archives </h3>
<% if @novations.to_a.empty? %>
  <div class="post">
    <p>No novations found...</p>
  </div>
<% else %>
  <% current_month = 0 %>  
  <% current_year = 0 %>
  <% for novation in @novations %> 
    <% if (novation.created_at.year != current_year)
     current_year = novation.created_at.year %>
    <h3 class="archiveyear"><%= novation.created_at.year%></h3>
<% end %>
<% if (novation.created_at.month != current_month || novation.created_at.year != current_year) 
 current_month = novation.created_at.month 
 current_year = novation.created_at.year %>  

<h4 class="archivemonth"><%= (Date::MONTHNAMES[novation.created_at.month]) %></h4>
<% end %>
<div class="archivepost">
  <%= link_to novation.heading, novation_path(novation) %> on <%= novation.created_at.strftime('%A')%> - <%= novation.created_at.strftime('%d') + "th"%>
</div>
<% end -%>
<% end %>
<p>
  <%= link_to 'Back', :back, class: "btn btn-default navbar-btn" %> <!--pages_path -->
</p>

app/views/novations/edit.html.erb
<h1>Editing Novation</h1>

<%= form_for(@novation) do |f| %>
<p>
<%= f.text_field :heading %>
</p>
<p>
<%= f.text_area :subject %>
</p>

<%= f.submit "Update" %>
<% end %>

<p>
  <%= link_to 'Back', :back %>
</p>

app/views/novations/index.html.erb
<div class="row">

<table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Heading</th>
      </tr>
    </thead>
    <tbody>
    <% @novations.each do |novation| %>
      <tr>
        <td class="col-md-1"><strong><%= novation.created_at.strftime("%d.%m.%Y") %></strong></td>
        <td class="col-md-11"><%= link_to novation.heading, novation_path(novation) %></td>
      </tr>
      <% end %>
    </tbody>
</table>


<p>
<%= link_to "Archive", new_page_path, class: "btn btn-default navbar-btn" %>
</p>

   
</div>

app/views/novations/new.html.erb
<h1>New Novation</h1>
<%= form_for :novation, url: novations_path do |f| %>
<%= f.hidden_field :page_id, :value => 3 %>
 
 <% if @novation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@novation.errors.count, "error") %> prohibited
        this novation from being saved:
      </h2>
      <ul>
        <% @novation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :heading %><br>
    <%= f.text_field :heading %>
  </p>
 
  <p>
    <%= f.label :subject %><br>
    <%= f.text_area :subject %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<p>
  <%= link_to 'Back', :back %> <!--novations_path-->
</p>

app/views/novations/show.html.erb
<p>
  <strong>Heading:</strong>
  <%= @novation.heading %>
</p>
 
<p>
  <strong>Subject:</strong>
  <%= @novation.subject %>
</p>

<p>
  <%= link_to 'Back', :back, class: "btn btn-default navbar-btn" %> <!--pages_path -->
</p>

app/views/pages/_menu.html.erb
<!--<%= link_to "school cms", root_path, id: "logo" %>-->
<nav>
  <ul class="nav nav-pills nav-stacked" style="padding-top: 9px;">
    <% @pages.each do |page| %>
      <li  class="<%= 'active' if current_page?(page_path(page)) %> text-uppercase">
        <%= link_to page.title, page_path(page) %>
        <%= link_to '', edit_page_path(page), class: "glyphicon glyphicon-pencil", id: "menu-editing" %>
        <%= link_to '', page_path(page),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove", id: "menu-editing" %>
      </li>
    <% end %>
  </ul>
  <%= link_to "New Page", new_page_path, class: "btn btn-default navbar-btn nav-justified" %>
</nav>

app/views/pages/_updated.html.erb
<div class="panel panel-default panel-body" id="callout-danger">
  Data are updated <%= @page.updated_at.strftime("%d.%m.%Y") %> and are actual on <%= @today %>
</div>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= form_for(@page) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <%= f.submit "Update Page" %>
<% end %>

<p>
  <%= link_to 'Back', :back %> <!--pages_path -->
</p>

app/views/pages/index.html.erb
<% @pages.each do |page| %>
<%= link_to page.title, page_path(page) %>
<%= link_to "Edit Page", edit_page_path(page) %>
<!--<%= page.title %>-->
<%= link_to '| Destroy', page_path(page),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
<br>
<% end %>
<p>
<%= link_to "New Page", new_page_path %>
</p>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= form_for :page, url: pages_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<p>
  <%= link_to 'Back', :back %> <!--pages_path -->
</p>

app/views/pages/show.html.erb
<div class="container-fluid">
<div class="row">
  <div class="col-md-2">
    <%= render 'menu' %>
  </div>

  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="long-art"></div>
      <div class="container">
        <%= link_to "school cms", '#', id: "logo" %>
        <div id="page-name" class="center">
        <%= @page.title %><%= link_to '', new_novation_path, class: "glyphicon glyphicon-plus-sign pull-right", id: "new" if @page.title == "Novations" %>
        <%= link_to '', new_page_article_path(@page), class: "glyphicon glyphicon-plus-sign pull-right", id: "new" if @page.title == "Articles" %>
        </div>
      </div>
  </header>

  <div class="col-md-10">

    <%= render "updated" if @page.title == "Articles" %>

    <div class="jumbotron col-md-12">
      <%= @page.content if @page.title != "Novations" && @page.title != "Articles" %>
      
      <ul class="col-md-12">
      <div class="panel-group" id="accordion">
      <% @articles.each_with_index do |article, index| %>
          <div class="panel panel-default">

            <div class="panel-heading">
              <h4 class="panel-title">
                <li>
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= index+1 %>"><%= article.item %></a>
                  <%= link_to '', edit_article_path(article), class: "glyphicon glyphicon-pencil", id: "pencil-remove" %>
                  <%= link_to '', article_path(article),
                      method: :delete,
                      data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove", id: "pencil-remove" %>
                </li>
              </h4>
            </div>

            <div id="collapse<%= index+1 %>" class="panel-collapse collapse">
              <div class="panel-body">
                <p><%= article.description %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      </ul>

      <% @novations.each do |novation| %>
        <div class="list-group-item"><%= novation.created_at.strftime("%d.%m.%Y") %>
          <strong><%= novation.heading %></strong>
          <%= link_to '', edit_novation_path(novation), class: "glyphicon glyphicon-pencil", id: "pencil-remove" %>
          <%= link_to '', novation_path(novation),
                  method: :delete,
                  data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove", id: "pencil-remove" %>
        </div>
        <br>
          <%= novation.subject %>
          <hr>
      <% end %>
      <p>
        <%= link_to "Archives", archives_path, class: "btn btn-default navbar-btn" if @page.title == "Novations" %>
      </p>
    </div>
  </div>
</div>
</div>